"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from .connection import is_connection_dropped
from .request import make_headers
from .response import is_fp_closed
from .ssl_ import HAS_SNI, IS_PYOPENSSL, IS_SECURETRANSPORT, PROTOCOL_TLS, SSLContext, assert_fingerprint, resolve_cert_reqs, resolve_ssl_version, ssl_wrap_socket
from .timeout import Timeout, current_time
from .retry import Retry
from .url import Url, get_host, parse_url, split_first
from .wait import wait_for_read, wait_for_write

