"""
This type stub file was generated by pyright.
"""

import sys

class NoWayToWaitForSocketError(Exception):
    ...


if sys.version_info >= (3, 5):
    ...
else:
    ...
def select_wait_for_socket(sock, read=..., write=..., timeout=...):
    ...

def poll_wait_for_socket(sock, read=..., write=..., timeout=...):
    ...

def null_wait_for_socket(*args, **kwargs):
    ...

def wait_for_socket(*args, **kwargs):
    ...

def wait_for_read(sock, timeout=...):
    """ Waits for reading to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    ...

def wait_for_write(sock, timeout=...):
    """ Waits for writing to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    ...

